FROM jenkins/jenkins:2.541.3-jdk21

USER root

RUN apt-get update \
  && apt-get install -y ca-certificates curl tar \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/java/openjdk-17 \
  && curl -fsSL "https://api.adoptium.net/v3/binary/latest/17/ga/linux/x64/jdk/hotspot/normal/eclipse?project=jdk" \
    | tar -xz --strip-components=1 -C /opt/java/openjdk-17

USER jenkins
